# 04 - Analisis de sensibilidad | RADAR Cibest

**Fase ASUM-DM:** 5 - Evaluacion  
**Objetivo:** Validar robustez del ranking ante perturbaciones de pesos y comparar TOPSIS vs VIKOR

In [ ]:
import sys
import re
from pathlib import Path
from typing import Optional, Union

import src
sys.path.insert(0, str(Path.cwd().parent))

import pandas as pd
import importlib


from src.utils import load_all_configs, get_variable_catalog, resolve_data_path
from src.scoring.sensitivity import run_sensitivity_analysis, compare_topsis_vikor
from src.scoring.hybrid_scorer import prepare_decision_matrix, run_full_scoring
from src.scoring.weighting import compute_hierarchical_weights
import src.scoring.monte_carlo as monte_carlo

importlib.invalidate_caches()
importlib.reload(monte_carlo)
importlib.reload(src.scoring.hybrid_scorer)
importlib.reload(src.scoring.sensitivity)  



from src.scoring.monte_carlo import (
    coerce_component_series,
    run_monte_carlo_topsis_robustness,
    run_monte_carlo_radar_robustness,
)

configs = load_all_configs()
catalog = get_variable_catalog(configs['variables'])

In [54]:
# ---------------------------------------------------------------------
# Cargar master correcto: master_raw_YYYYMMDD.parquet
# ---------------------------------------------------------------------
raw_dir = resolve_data_path(configs["settings"]["data"]["raw_path"])

pattern = re.compile(r"^master_raw_\d{8}\.parquet$")

master_files = sorted(
    [
        p for p in raw_dir.glob("master_raw_*.parquet")
        if pattern.match(p.name)
    ],
    key=lambda p: p.stat().st_mtime,
    reverse=True,
)

if not master_files:
    raise FileNotFoundError(
        "Falta master_raw_YYYYMMDD.parquet. Ejecute primero notebook 01."
    )

master_path = master_files[0]
master = pd.read_parquet(master_path)

print(f"Archivo master cargado: {master_path.name}")
print(f"Master cargado: {master.shape}")
print(f"Variables únicas: {master['variable'].nunique()}")
print("Tiene gdp_growth:", "gdp_growth" in master["variable"].astype(str).str.strip().unique())

# ---------------------------------------------------------------------
# Limpieza defensiva
# ---------------------------------------------------------------------
master = master.copy()
master["variable"] = master["variable"].astype(str).str.strip()

# Eliminar wgi_composite si quedó de versiones anteriores
master = master[master["variable"] != "wgi_composite"].copy()

# ---------------------------------------------------------------------
# Validar matriz de decisión
# ---------------------------------------------------------------------
wide_raw, decision_matrix, excluded = prepare_decision_matrix(master, configs)

print(f"wide_raw: {wide_raw.shape}")
print(f"Decision matrix: {decision_matrix.shape}")
print(f"Países excluidos: {excluded}")

2026-06-12 16:12:20.740 | INFO     | src.data_preparation.cleaning:pivot_long_to_wide:70 - Pivoteo ancho: 30 paises x 45 variables (estrategia=latest_available)
2026-06-12 16:12:20.746 | WARNING  | src.data_preparation.cleaning:validate_country_coverage:92 - Paises excluidos por >30% variables faltantes: ['CUB']
2026-06-12 16:12:20.855 | INFO     | src.data_preparation.cleaning:impute_missing:145 - Imputacion (regional_median): 107 -> 0 celdas faltantes
2026-06-12 16:12:20.858 | INFO     | src.data_preparation.cleaning:run_cleaning:183 - Limpieza completada: 29 paises x 45 variables
2026-06-12 16:12:20.867 | INFO     | src.data_preparation.feature_engineering:apply_log_transform:73 - Log-transformacion (natural) aplicada a: ['gdp_nominal', 'population_total', 'geographic_distance_km', 'colombian_diaspora_stock', 'stock_market_cap_gdp', 'financial_system_deposits_gdp', 'domestic_credit_private_gdp', 'fdi_net_inflows_gdp', 'personal_remittances_gdp', 'secure_internet_servers_per_million', 'atms_per_100k_adults', 'commercial_bank_branches_per_100k_adults']
2026-06-12 16:12:20.876 | INFO     | src.data_preparation.feature_engineering:run_feature_engineering:136 - Feature engineering completado: 29 paises x 46 variables
2026-06-12 16:12:20.877 | INFO     | src.scoring.hybrid_scorer:prepare_decision_matrix:109 - Variables excluidas de TOPSIS: ['colombian_diaspora_stock', 'common_language_spanish', 'cultural_distance_hofstede', 'gdp_growth', 'geographic_distance_km', 'hofstede_idv', 'hofstede_ivr', 'hofstede_lto', 'hofstede_mas', 'hofstede_pdi', 'hofstede_uai']
2026-06-12 16:12:20.881 | INFO     | src.data_preparation.normalization:normalize:107 - Normalizacion min_max: 29 paises x 35 variables
2026-06-12 16:12:20.884 | INFO     | src.data_preparation.normalization:apply_direction:74 - Direccion aplicada: 8 variables invertidas -> ['inflation_rate', 'unemployment_rate', 'public_debt_gdp', 'weighted_mean_applied_tariff_all_products', 'interest_rate_spread', 'bank_npl_ratio', 'bank_concentration_5', 'country_risk_premium']

Archivo master cargado: master_raw_20260612.parquet
Master cargado: (1281, 5)
Variables únicas: 45
Tiene gdp_growth: True
wide_raw: (29, 46)
Decision matrix: (29, 35)
Países excluidos: ['CUB']

## 1. Sensibilidad de pesos

In [55]:
sens = run_sensitivity_analysis(
    decision_matrix=decision_matrix,
    dimension_weights=configs['weights']['dimension_weights'],
    variable_weights_by_dim=configs['weights']['variable_weights'],
    variable_catalog=catalog,
)
sens

2026-06-12 16:12:21.000 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 29 paises | score max=0.719 (CAN)
2026-06-12 16:12:21.018 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 29 paises | score max=0.725 (CAN)
2026-06-12 16:12:21.035 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 29 paises | score max=0.722 (CAN)
2026-06-12 16:12:21.050 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 29 paises | score max=0.716 (CAN)
2026-06-12 16:12:21.071 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 29 paises | score max=0.715 (USA)
2026-06-12 16:12:21.091 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 29 paises | score max=0.730 (CAN)
2026-06-12 16:12:21.105 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 29 paises | score max=0.725 (CAN)
2026-06-12 16:12:21.122 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 29 paises | score max=0.714 (USA)
2026-06-12 16:12:21.137 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 29 paises | score max=0.711 (USA)
2026-06-12 16:12:21.154 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 29 paises | score max=0.707 (USA)
2026-06-12 16:12:21.171 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 29 paises | score max=0.712 (USA)
2026-06-12 16:12:21.189 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 29 paises | score max=0.728 (CAN)
2026-06-12 16:12:21.208 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 29 paises | score max=0.737 (CAN)
2026-06-12 16:12:21.227 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 29 paises | score max=0.721 (CAN)
2026-06-12 16:12:21.246 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 29 paises | score max=0.720 (CAN)
2026-06-12 16:12:21.263 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 29 paises | score max=0.718 (CAN)
2026-06-12 16:12:21.296 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 29 paises | score max=0.718 (USA)
2026-06-12 16:12:21.305 | INFO     | src.scoring.sensitivity:run_sensitivity_analysis:85 - Sensibilidad: corr Spearman media = 0.995 | overlap top-10 medio = 9.8

,dimension,perturbation,score_corr,topN_overlap,topN_size,countries_in,countries_out
0,macro,0.8,0.9887,10,10,,
1,macro,0.9,0.9931,10,10,,
2,macro,1.1,0.9980,9,10,BRA,JAM
3,macro,1.2,0.9862,9,10,BRA,JAM
4,financial,0.8,0.9966,9,10,BRA,JAM
5,financial,0.9,0.9985,10,10,,
6,financial,1.1,0.9966,10,10,,
7,financial,1.2,0.9911,10,10,,
8,institutional,0.8,0.9901,10,10,,
9,institutional,0.9,0.9966,10,10,,
10,institutional,1.1,0.9951,10,10,,
11,institutional,1.2,0.9946,10,10,,
12,digital_tech,0.8,0.9985,10,10,,
13,digital_tech,0.9,0.9990,10,10,,
14,digital_tech,1.1,0.9985,10,10,,
15,digital_tech,1.2,0.9956,10,10,,

## 2. Comparacion TOPSIS vs VIKOR

In [56]:
var_weights = compute_hierarchical_weights(
    configs['weights']['dimension_weights'],
    configs['weights']['variable_weights'],
)
var_weights = {k: v for k, v in var_weights.items() if k in decision_matrix.columns}
comparison = compare_topsis_vikor(decision_matrix, var_weights, catalog)
comparison.head(15)

2026-06-12 16:12:21.404 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 29 paises | score max=0.719 (CAN)
2026-06-12 16:12:21.424 | INFO     | src.scoring.ranking:rank:180 - VIKOR completado: 29 paises | v=0.5
2026-06-12 16:12:21.436 | INFO     | src.scoring.sensitivity:compare_topsis_vikor:114 - TOPSIS vs VIKOR: correlacion Spearman = 0.930

              score_topsis  rank_topsis  score_vikor  rank_vikor  rank_diff
country_iso3
CAN               0.719156            1     1.000000           1          0
USA               0.717864            2     0.996111           2          0
ESP               0.665248            3     0.960261           3          0
CHL               0.636569            4     0.873094           4          0
URY               0.589495            5     0.758503           5          0
CRI               0.581929            6     0.731742           6          0
BHS               0.557503            7     0.503709          14          7
PAN               0.557322            8     0.727145           7          1
DOM               0.549547            9     0.639350           8          1
JAM               0.548609           10     0.437690          18          8
BRA               0.537553           11     0.541718          11          0
MEX               0.529872           12     0.601742           9          3
BRB               0.528224           13     0.371037          20          7
TTO               0.528185           14     0.531084          12          2
GUY               0.512394           15     0.500918          15          0

## Simulación de Motecarlo

### Preparar IPC y Trending para Monte Carlo

In [57]:
results = run_full_scoring(master, configs, persist=True)

2026-06-12 16:12:21.495 | INFO     | src.data_preparation.cleaning:pivot_long_to_wide:70 - Pivoteo ancho: 30 paises x 45 variables (estrategia=latest_available)

2026-06-12 16:12:21.503 | WARNING  | src.data_preparation.cleaning:validate_country_coverage:92 - Paises excluidos por >30% variables faltantes: ['CUB']
2026-06-12 16:12:21.622 | INFO     | src.data_preparation.cleaning:impute_missing:145 - Imputacion (regional_median): 107 -> 0 celdas faltantes
2026-06-12 16:12:21.624 | INFO     | src.data_preparation.cleaning:run_cleaning:183 - Limpieza completada: 29 paises x 45 variables
2026-06-12 16:12:21.633 | INFO     | src.data_preparation.feature_engineering:apply_log_transform:73 - Log-transformacion (natural) aplicada a: ['gdp_nominal', 'population_total', 'geographic_distance_km', 'colombian_diaspora_stock', 'stock_market_cap_gdp', 'financial_system_deposits_gdp', 'domestic_credit_private_gdp', 'fdi_net_inflows_gdp', 'personal_remittances_gdp', 'secure_internet_servers_per_million', 'atms_per_100k_adults', 'commercial_bank_branches_per_100k_adults']
2026-06-12 16:12:21.638 | INFO     | src.data_preparation.feature_engineering:run_feature_engineering:136 - Feature engineering completado: 29 paises x 46 variables
2026-06-12 16:12:21.639 | INFO     | src.scoring.hybrid_scorer:prepare_decision_matrix:109 - Variables excluidas de TOPSIS: ['colombian_diaspora_stock', 'common_language_spanish', 'cultural_distance_hofstede', 'gdp_growth', 'geographic_distance_km', 'hofstede_idv', 'hofstede_ivr', 'hofstede_lto', 'hofstede_mas', 'hofstede_pdi', 'hofstede_uai']
2026-06-12 16:12:21.643 | INFO     | src.data_preparation.normalization:normalize:107 - Normalizacion min_max: 29 paises x 35 variables
2026-06-12 16:12:21.646 | INFO     | src.data_preparation.normalization:apply_direction:74 - Direccion aplicada: 8 variables invertidas -> ['inflation_rate', 'unemployment_rate', 'public_debt_gdp', 'weighted_mean_applied_tariff_all_products', 'interest_rate_spread', 'bank_npl_ratio', 'bank_concentration_5', 'country_risk_premium']
2026-06-12 16:12:21.697 | INFO     | src.scoring.hybrid_scorer:run_full_scoring:846 - País origen excluido del scoring (post-feature engineering): COL. Países 29 -> 28
2026-06-12 16:12:21.713 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.719 (CAN)
2026-06-12 16:12:21.714 | INFO     | src.scoring.hybrid_scorer:score_all_business_lines:240 - --- TOPSIS linea IB ---
2026-06-12 16:12:21.736 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.784 (CAN)
2026-06-12 16:12:21.737 | INFO     | src.scoring.hybrid_scorer:score_all_business_lines:240 - --- TOPSIS linea PF ---
2026-06-12 16:12:21.762 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.669 (ESP)
2026-06-12 16:12:21.766 | INFO     | src.scoring.hybrid_scorer:score_all_business_lines:240 - --- TOPSIS linea AD ---
2026-06-12 16:12:21.796 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.798 (USA)
2026-06-12 16:12:21.799 | INFO     | src.scoring.hybrid_scorer:score_all_business_lines:240 - --- TOPSIS linea BD ---
2026-06-12 16:12:21.831 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.796 (USA)
2026-06-12 16:12:21.833 | INFO     | src.scoring.hybrid_scorer:score_all_business_lines:240 - --- TOPSIS linea CIB ---
2026-06-12 16:12:21.857 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.753 (CAN)
2026-06-12 16:12:21.860 | INFO     | src.scoring.gravity:compute_ipc:65 - IPC se calculara con 4 componentes: ['geographic_distance_km', 'cultural_distance_hofstede', 'common_language_spanish', 'colombian_diaspora_stock']
2026-06-12 16:12:21.865 | INFO     | src.scoring.gravity:compute_ipc:92 - IPC calculado: top-3 afinidad -> {'ECU': 0.997, 'PAN': 0.981, 'VEN': 0.892}
2026-06-12 16:12:21.866 | INFO     | src.scoring.hybrid_scorer:run_full_scoring:885 - Método de tendencia configurado: gdp_growth | enabled=True | variable=gdp_growth
2026-06-12 16:12:21.868 | INFO     | src.scoring.hybrid_scorer:compute_trend_factor:574 - Calculando tendencia con variable=gdp_growth. Filas encontradas=90
2026-06-12 16:12:21.872 | INFO     | src.scoring.hybrid_scorer:compute_trend_factor:619 - Ventana tendencia gdp_growth: 2022-2024
2026-06-12 16:12:21.875 | INFO     | src.scoring.hybrid_scorer:compute_trend_factor:631 - Filas en ventana de tendencia: 90
2026-06-12 16:12:21.881 | INFO     | src.scoring.hybrid_scorer:compute_trend_factor:694 - Winsorización aplicada a tendencia gdp_growth: q_low=0.05, q_high=0.95, lower=1.1757, upper=7.3462
2026-06-12 16:12:21.882 | INFO     | src.scoring.hybrid_scorer:compute_trend_factor:711 - Resumen trend_raw gdp_growth: min=1.1757, max=7.3462, rango=6.1704
2026-06-12 16:12:21.884 | INFO     | src.scoring.hybrid_scorer:compute_trend_factor:737 - Factor de tendencia calculado con gdp_growth, ventana=3 años, países=28
2026-06-12 16:12:22.025 | INFO     | src.scoring.hybrid_scorer:_persist_results:1070 - Resultados persistidos en C:\Users\jadarve\OneDrive - Grupo Bancolombia\Bancolombia\GFEC-VEF\2026\Internacionalización\radar_cibest_v2\data\scores con timestamp 20260612

In [58]:
ipc_scores = coerce_component_series(
    results["ipc"],
    value_col=None,
    component_name="ipc",
)

trend_scores = coerce_component_series(
    results["trend"],
    value_col="trend",
    component_name="trend",
)

### Ejecutar Monte Carlo TOPSIS

In [59]:
mc_cfg = configs["settings"].get("monte_carlo", {})

mc_topsis = run_monte_carlo_topsis_robustness(
    decision_matrix=decision_matrix,
    configs=configs,
    variable_catalog=catalog,
    n_simulations=int(mc_cfg.get("n_simulations", 1000)),
    dimension_concentration=float(
        mc_cfg.get("topsis", {}).get("dimension_concentration", 150)
    ),
    variable_concentration=float(
        mc_cfg.get("topsis", {}).get("variable_concentration", 100)
    ),
    random_seed=int(mc_cfg.get("random_seed", 42)),
)

2026-06-12 16:12:22.085 | INFO     | src.scoring.monte_carlo:run_monte_carlo_topsis_robustness:576 - País origen excluido de Monte Carlo TOPSIS: COL
2026-06-12 16:12:22.104 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.787 (CAN)
2026-06-12 16:12:22.127 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.648 (ESP)
2026-06-12 16:12:22.153 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.795 (USA)
2026-06-12 16:12:22.175 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.775 (USA)
2026-06-12 16:12:22.193 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.742 (CAN)
2026-06-12 16:12:22.216 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.725 (CAN)
2026-06-12 16:12:22.239 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.627 (ESP)
2026-06-12 16:12:22.262 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.781 (USA)
2026-06-12 16:12:22.282 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.763 (USA)
2026-06-12 16:12:22.301 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.761 (CAN)
2026-06-12 16:12:22.323 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.798 (CAN)
2026-06-12 16:12:22.343 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.687 (ESP)
2026-06-12 16:12:22.365 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.801 (USA)
2026-06-12 16:12:22.393 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.813 (USA)
2026-06-12 16:12:22.419 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.754 (CAN)
2026-06-12 16:12:22.444 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.753 (CAN)
2026-06-12 16:12:22.461 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.669 (ESP)
2026-06-12 16:12:22.477 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.829 (USA)
2026-06-12 16:12:22.499 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.782 (USA)
2026-06-12 16:12:22.524 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.768 (CAN)
2026-06-12 16:12:22.551 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.762 (CAN)
2026-06-12 16:12:22.579 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.658 (ESP)
2026-06-12 16:12:22.595 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.806 (USA)
2026-06-12 16:12:22.610 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.824 (USA)
2026-06-12 16:12:22.630 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.723 (CAN)
2026-06-12 16:12:22.654 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.823 (CAN)
2026-06-12 16:12:22.672 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.662 (ESP)
2026-06-12 16:12:22.698 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.792 (USA)
2026-06-12 16:12:22.717 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.793 (USA)
2026-06-12 16:12:22.735 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.758 (CAN)
2026-06-12 16:12:22.756 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.809 (CAN)
2026-06-12 16:12:22.772 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.611 (ESP)
2026-06-12 16:12:22.792 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.790 (USA)
2026-06-12 16:12:22.812 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.786 (USA)
2026-06-12 16:12:22.837 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.702 (CAN)
2026-06-12 16:12:22.872 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.776 (CAN)
2026-06-12 16:12:22.892 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.680 (ESP)
2026-06-12 16:12:22.910 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.779 (USA)
2026-06-12 16:12:22.936 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.799 (USA)
2026-06-12 16:12:22.981 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.742 (CAN)
2026-06-12 16:12:23.031 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.776 (CAN)
2026-06-12 16:12:23.056 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.618 (ESP)
2026-06-12 16:12:23.081 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.818 (USA)
2026-06-12 16:12:23.104 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.809 (USA)
2026-06-12 16:12:23.130 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.779 (CAN)
2026-06-12 16:12:23.150 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.751 (CAN)
2026-06-12 16:12:23.169 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.676 (ESP)
2026-06-12 16:12:23.186 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.817 (USA)
2026-06-12 16:12:23.207 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.805 (USA)
2026-06-12 16:12:23.223 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.781 (CAN)
2026-06-12 16:12:23.239 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.786 (CAN)
2026-06-12 16:12:23.254 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.686 (ESP)
2026-06-12 16:12:23.268 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.789 (USA)
2026-06-12 16:12:23.282 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.834 (USA)
2026-06-12 16:12:23.299 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.767 (CAN)
2026-06-12 16:12:23.323 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.803 (CAN)
2026-06-12 16:12:23.349 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.695 (ESP)
2026-06-12 16:12:23.370 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.740 (USA)
2026-06-12 16:12:23.389 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.821 (USA)
2026-06-12 16:12:23.406 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.744 (CAN)
2026-06-12 16:12:23.431 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.797 (CAN)
2026-06-12 16:12:23.448 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.632 (ESP)
2026-06-12 16:12:23.463 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.781 (USA)
2026-06-12 16:12:23.481 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.762 (USA)
2026-06-12 16:12:23.497 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.796 (CAN)
2026-06-12 16:12:23.516 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.753 (CAN)
2026-06-12 16:12:23.537 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.668 (ESP)
2026-06-12 16:12:23.554 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.799 (USA)
2026-06-12 16:12:23.570 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.801 (USA)
2026-06-12 16:12:23.588 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.739 (CAN)
2026-06-12 16:12:23.619 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.763 (CAN)
2026-06-12 16:12:23.638 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.657 (ESP)
2026-06-12 16:12:23.654 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.802 (USA)
2026-06-12 16:12:23.669 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.819 (USA)
2026-06-12 16:12:23.688 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.764 (CAN)
2026-06-12 16:12:23.710 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.758 (CAN)
2026-06-12 16:12:23.727 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.654 (ESP)
2026-06-12 16:12:23.744 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.802 (USA)
2026-06-12 16:12:23.758 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.802 (USA)
2026-06-12 16:12:23.795 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.739 (CAN)
2026-06-12 16:12:23.821 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.737 (CAN)
2026-06-12 16:12:23.847 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.637 (ESP)
2026-06-12 16:12:23.860 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.840 (USA)
2026-06-12 16:12:23.877 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.729 (USA)
2026-06-12 16:12:23.895 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.733 (CAN)
2026-06-12 16:12:23.913 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.789 (CAN)
2026-06-12 16:12:23.929 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.699 (ESP)
2026-06-12 16:12:23.943 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.741 (USA)
2026-06-12 16:12:23.958 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.792 (USA)
2026-06-12 16:12:23.972 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.770 (CAN)
2026-06-12 16:12:23.988 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.843 (CAN)
2026-06-12 16:12:24.002 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.699 (ESP)
2026-06-12 16:12:24.017 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.799 (USA)
2026-06-12 16:12:24.031 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.802 (USA)
2026-06-12 16:12:24.047 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.756 (CAN)
2026-06-12 16:12:24.064 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.787 (CAN)
2026-06-12 16:12:24.079 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.605 (ESP)
2026-06-12 16:12:24.092 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.779 (USA)
2026-06-12 16:12:24.107 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.803 (USA)
2026-06-12 16:12:24.123 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.770 (CAN)
2026-06-12 16:12:24.149 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.819 (CAN)
2026-06-12 16:12:24.163 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.685 (ESP)
2026-06-12 16:12:24.182 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.807 (USA)
2026-06-12 16:12:24.198 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.804 (USA)
2026-06-12 16:12:24.215 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.757 (CAN)
2026-06-12 16:12:24.231 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.781 (CAN)
2026-06-12 16:12:24.247 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.693 (ESP)
2026-06-12 16:12:24.264 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.814 (USA)
2026-06-12 16:12:24.280 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.793 (USA)
2026-06-12 16:12:24.295 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.646 (CAN)
2026-06-12 16:12:24.321 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.800 (CAN)
2026-06-12 16:12:24.337 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.655 (ESP)
2026-06-12 16:12:24.353 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.772 (USA)
2026-06-12 16:12:24.370 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.765 (USA)
2026-06-12 16:12:24.389 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.768 (CAN)
2026-06-12 16:12:24.407 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.805 (CAN)
2026-06-12 16:12:24.426 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.646 (ESP)
2026-06-12 16:12:24.440 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.786 (USA)
2026-06-12 16:12:24.457 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.760 (USA)
2026-06-12 16:12:24.473 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.737 (CAN)
2026-06-12 16:12:24.490 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.803 (CAN)
2026-06-12 16:12:24.506 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.651 (ESP)
2026-06-12 16:12:24.521 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.787 (USA)
2026-06-12 16:12:24.539 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.854 (USA)
2026-06-12 16:12:24.567 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.722 (CAN)
2026-06-12 16:12:24.581 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.786 (CAN)
2026-06-12 16:12:24.596 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.691 (ESP)
2026-06-12 16:12:24.610 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.801 (USA)
2026-06-12 16:12:24.624 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.831 (USA)
2026-06-12 16:12:24.640 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.788 (CAN)
2026-06-12 16:12:24.671 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.789 (CAN)
2026-06-12 16:12:24.698 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.684 (ESP)
2026-06-12 16:12:24.726 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.824 (USA)
2026-06-12 16:12:24.754 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.813 (USA)
2026-06-12 16:12:24.788 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.695 (CAN)
2026-06-12 16:12:24.821 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.802 (CAN)
2026-06-12 16:12:24.861 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.616 (ESP)
2026-06-12 16:12:24.894 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.793 (USA)
2026-06-12 16:12:24.922 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.763 (USA)
2026-06-12 16:12:24.954 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.755 (CAN)
2026-06-12 16:12:24.989 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.738 (CAN)
2026-06-12 16:12:25.017 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.663 (ESP)
2026-06-12 16:12:25.047 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.822 (USA)
2026-06-12 16:12:25.068 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.778 (USA)
2026-06-12 16:12:25.092 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.689 (CAN)
2026-06-12 16:12:25.127 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.794 (CAN)
2026-06-12 16:12:25.152 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.677 (ESP)
2026-06-12 16:12:25.168 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.803 (USA)
2026-06-12 16:12:25.183 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.800 (USA)
2026-06-12 16:12:25.198 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.781 (CAN)
2026-06-12 16:12:25.218 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.766 (CAN)
2026-06-12 16:12:25.234 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.718 (ESP)
2026-06-12 16:12:25.249 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.797 (USA)
2026-06-12 16:12:25.263 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.826 (USA)
2026-06-12 16:12:25.276 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.730 (CAN)
2026-06-12 16:12:25.295 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.780 (CAN)
2026-06-12 16:12:25.306 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.700 (ESP)
2026-06-12 16:12:25.321 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.827 (USA)
2026-06-12 16:12:25.338 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.781 (USA)
2026-06-12 16:12:25.354 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.715 (CAN)
2026-06-12 16:12:25.368 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.783 (CAN)
2026-06-12 16:12:25.381 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.687 (ESP)
2026-06-12 16:12:25.399 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.811 (USA)
2026-06-12 16:12:25.414 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.781 (USA)

### Ejecutar Monte Carlo RADAR

In [61]:
mc_radar = run_monte_carlo_radar_robustness(
    decision_matrix=decision_matrix,
    configs=configs,
    variable_catalog=catalog,
    ipc_scores=ipc_scores,
    trend_scores=trend_scores,
    n_simulations=int(mc_cfg.get("n_simulations", 1000)),
    dimension_concentration=float(
        mc_cfg.get("topsis", {}).get("dimension_concentration", 150)
    ),
    variable_concentration=float(
        mc_cfg.get("topsis", {}).get("variable_concentration", 100)
    ),
    composite_concentration=float(
        mc_cfg.get("radar", {}).get("composite_concentration", 150)
    ),
    perturb_composite_weights=bool(
        mc_cfg.get("radar", {}).get("perturb_composite_weights", True)
    ),
    random_seed=int(mc_cfg.get("random_seed", 42)),
)

2026-06-12 16:14:50.234 | INFO     | src.scoring.monte_carlo:run_monte_carlo_radar_robustness:739 - País origen excluido de Monte Carlo RADAR: COL
2026-06-12 16:14:50.267 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.773 (CAN)
2026-06-12 16:14:50.289 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.665 (ESP)
2026-06-12 16:14:50.314 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.820 (USA)
2026-06-12 16:14:50.336 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.737 (ESP)
2026-06-12 16:14:50.359 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.743 (CAN)
2026-06-12 16:14:50.381 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.727 (CAN)
2026-06-12 16:14:50.402 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.694 (ESP)
2026-06-12 16:14:50.429 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.807 (USA)
2026-06-12 16:14:50.452 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.819 (USA)
2026-06-12 16:14:50.475 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.722 (CAN)
2026-06-12 16:14:50.496 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.775 (CAN)
2026-06-12 16:14:50.515 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.643 (ESP)
2026-06-12 16:14:50.538 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.782 (USA)
2026-06-12 16:14:50.559 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.805 (USA)
2026-06-12 16:14:50.582 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.757 (CAN)
2026-06-12 16:14:50.603 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.795 (CAN)
2026-06-12 16:14:50.624 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.707 (ESP)
2026-06-12 16:14:50.644 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.832 (USA)
2026-06-12 16:14:50.665 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.793 (USA)
2026-06-12 16:14:50.683 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.715 (CAN)
2026-06-12 16:14:50.703 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.803 (CAN)
2026-06-12 16:14:50.722 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.670 (ESP)
2026-06-12 16:14:50.763 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.793 (USA)
2026-06-12 16:14:50.825 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.793 (USA)
2026-06-12 16:14:50.864 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.767 (CAN)
2026-06-12 16:14:50.886 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.786 (CAN)
2026-06-12 16:14:50.910 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.717 (ESP)
2026-06-12 16:14:50.931 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.781 (USA)
2026-06-12 16:14:50.951 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.809 (USA)
2026-06-12 16:14:50.976 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.733 (CAN)
2026-06-12 16:14:50.997 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.789 (CAN)
2026-06-12 16:14:51.019 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.670 (ESP)
2026-06-12 16:14:51.037 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.777 (USA)
2026-06-12 16:14:51.059 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.808 (USA)
2026-06-12 16:14:51.077 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.725 (CAN)
2026-06-12 16:14:51.096 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.790 (CAN)
2026-06-12 16:14:51.115 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.679 (ESP)
2026-06-12 16:14:51.134 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.788 (USA)
2026-06-12 16:14:51.152 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.808 (USA)
2026-06-12 16:14:51.170 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.780 (CAN)
2026-06-12 16:14:51.194 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.826 (CAN)
2026-06-12 16:14:51.213 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.653 (ESP)
2026-06-12 16:14:51.232 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.805 (USA)
2026-06-12 16:14:51.251 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.802 (USA)
2026-06-12 16:14:51.274 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.801 (CAN)
2026-06-12 16:14:51.293 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.794 (CAN)
2026-06-12 16:14:51.312 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.669 (ESP)
2026-06-12 16:14:51.328 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.783 (USA)
2026-06-12 16:14:51.348 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.820 (USA)
2026-06-12 16:14:51.367 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.739 (CAN)
2026-06-12 16:14:51.386 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.741 (CAN)
2026-06-12 16:14:51.402 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.749 (ESP)
2026-06-12 16:14:51.424 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.834 (USA)
2026-06-12 16:14:51.444 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.784 (USA)
2026-06-12 16:14:51.461 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.727 (CAN)
2026-06-12 16:14:51.479 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.816 (CAN)
2026-06-12 16:14:51.495 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.724 (ESP)
2026-06-12 16:14:51.512 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.837 (USA)
2026-06-12 16:14:51.530 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.807 (USA)
2026-06-12 16:14:51.548 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.753 (CAN)
2026-06-12 16:14:51.568 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.805 (CAN)
2026-06-12 16:14:51.593 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.692 (ESP)
2026-06-12 16:14:51.617 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.813 (USA)
2026-06-12 16:14:51.637 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.835 (USA)
2026-06-12 16:14:51.661 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.746 (CAN)
2026-06-12 16:14:51.684 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.696 (CAN)
2026-06-12 16:14:51.702 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.586 (SLV)
2026-06-12 16:14:51.724 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.829 (USA)
2026-06-12 16:14:51.743 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.746 (USA)
2026-06-12 16:14:51.762 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.780 (CAN)
2026-06-12 16:14:51.782 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.769 (CAN)
2026-06-12 16:14:51.803 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.643 (ESP)
2026-06-12 16:14:51.825 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.813 (USA)
2026-06-12 16:14:51.844 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.825 (USA)
2026-06-12 16:14:51.864 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.756 (CAN)
2026-06-12 16:14:51.884 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.800 (CAN)
2026-06-12 16:14:51.904 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.721 (ESP)
2026-06-12 16:14:51.927 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.802 (USA)
2026-06-12 16:14:51.947 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.825 (USA)
2026-06-12 16:14:51.970 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.817 (CAN)
2026-06-12 16:14:51.993 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.823 (CAN)
2026-06-12 16:14:52.013 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.678 (ESP)
2026-06-12 16:14:52.035 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.810 (USA)
2026-06-12 16:14:52.056 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.761 (USA)
2026-06-12 16:14:52.081 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.760 (CAN)
2026-06-12 16:14:52.106 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.830 (CAN)
2026-06-12 16:14:52.126 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.693 (ESP)
2026-06-12 16:14:52.148 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.801 (USA)
2026-06-12 16:14:52.168 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.778 (USA)
2026-06-12 16:14:52.187 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.764 (CAN)
2026-06-12 16:14:52.213 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.796 (CAN)
2026-06-12 16:14:52.237 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.668 (ESP)
2026-06-12 16:14:52.259 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.808 (USA)
2026-06-12 16:14:52.278 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.804 (USA)
2026-06-12 16:14:52.300 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.760 (CAN)
2026-06-12 16:14:52.325 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.780 (CAN)
2026-06-12 16:14:52.347 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.578 (JAM)
2026-06-12 16:14:52.367 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.788 (USA)
2026-06-12 16:14:52.389 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.831 (USA)
2026-06-12 16:14:52.411 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.688 (CAN)
2026-06-12 16:14:52.436 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.785 (CAN)
2026-06-12 16:14:52.461 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.676 (ESP)
2026-06-12 16:14:52.484 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.841 (USA)
2026-06-12 16:14:52.512 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.789 (USA)
2026-06-12 16:14:52.537 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.739 (CAN)
2026-06-12 16:14:52.578 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.834 (CAN)
2026-06-12 16:14:52.602 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.699 (ESP)
2026-06-12 16:14:52.625 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.828 (USA)
2026-06-12 16:14:52.663 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.787 (USA)
2026-06-12 16:14:52.717 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.777 (CAN)
2026-06-12 16:14:52.753 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.809 (CAN)
2026-06-12 16:14:52.830 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.681 (ESP)
2026-06-12 16:14:52.894 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.745 (USA)
2026-06-12 16:14:52.965 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.819 (USA)
2026-06-12 16:14:52.996 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.757 (CAN)
2026-06-12 16:14:53.041 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.739 (CAN)
2026-06-12 16:14:53.082 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.656 (ESP)
2026-06-12 16:14:53.112 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.791 (USA)
2026-06-12 16:14:53.143 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.783 (USA)
2026-06-12 16:14:53.175 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.745 (CAN)
2026-06-12 16:14:53.211 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.724 (CAN)
2026-06-12 16:14:53.264 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.643 (ESP)
2026-06-12 16:14:53.314 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.820 (USA)
2026-06-12 16:14:53.365 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.839 (USA)
2026-06-12 16:14:53.415 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.778 (CAN)
2026-06-12 16:14:53.446 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.698 (CAN)
2026-06-12 16:14:53.485 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.645 (ESP)
2026-06-12 16:14:53.531 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.799 (USA)
2026-06-12 16:14:53.567 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.819 (USA)
2026-06-12 16:14:53.618 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.780 (CAN)
2026-06-12 16:14:53.664 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.746 (CAN)
2026-06-12 16:14:53.714 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.722 (ESP)
2026-06-12 16:14:53.756 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.813 (USA)
2026-06-12 16:14:53.808 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.807 (USA)
2026-06-12 16:14:53.846 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.762 (CAN)
2026-06-12 16:14:53.905 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.793 (CAN)
2026-06-12 16:14:53.956 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.701 (ESP)
2026-06-12 16:14:53.982 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.820 (USA)
2026-06-12 16:14:54.011 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.807 (USA)
2026-06-12 16:14:54.039 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.737 (CAN)
2026-06-12 16:14:54.069 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.762 (CAN)
2026-06-12 16:14:54.098 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.666 (ESP)
2026-06-12 16:14:54.125 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.824 (USA)
2026-06-12 16:14:54.152 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.779 (USA)
2026-06-12 16:14:54.181 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.758 (CAN)
2026-06-12 16:14:54.214 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.780 (CAN)
2026-06-12 16:14:54.236 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.711 (ESP)
2026-06-12 16:14:54.261 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.808 (USA)
2026-06-12 16:14:54.302 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.775 (USA)
2026-06-12 16:14:54.368 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.804 (USA)
2026-06-12 16:14:54.428 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.797 (CAN)
2026-06-12 16:14:54.469 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.617 (ESP)
2026-06-12 16:14:54.501 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.763 (USA)
2026-06-12 16:14:54.544 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.730 (USA)
2026-06-12 16:14:54.572 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.746 (CAN)
2026-06-12 16:14:54.609 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.802 (CAN)
2026-06-12 16:14:54.636 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.655 (ESP)
2026-06-12 16:14:54.666 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.796 (USA)
2026-06-12 16:14:54.696 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.735 (USA)
2026-06-12 16:14:54.728 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.710 (CAN)
2026-06-12 16:14:54.935 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.808 (CAN)
2026-06-12 16:14:54.983 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.604 (ESP)
2026-06-12 16:14:55.036 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.827 (USA)
2026-06-12 16:14:55.070 | INFO     | src.scoring.ranking:rank:133 - TOPSIS completado: 28 paises | score max=0.784 (USA)

In [62]:
# Debería aproximarse a: n_simulations * n_business_lines * n_países_sin_COL
# 1000 * 5 * 28 = 140000
mc_radar["simulation_long"].shape

(140000, 12)

#### Consultas principales

#####  Robustez RADAR por línea

In [63]:
radar_rank_robustness = mc_radar["rank_robustness"]

radar_rank_robustness[
    radar_rank_robustness["business_line"] == "PF"
].sort_values("mean_rank").head(15)

,business_line,country_iso3,mean_rank,median_rank,std_rank,min_rank,max_rank,p10_rank,p90_rank,mean_score,std_score,p10_score,p90_score
112,PF,PAN,1.017,1.0,0.129336,1,2,1.0,1.0,0.700336,0.023151,0.670088,0.728815
113,PF,CRI,2.465,2.0,0.658186,2,4,2.0,3.0,0.640076,0.017124,0.618087,0.660862
114,PF,ESP,3.347,3.0,1.247456,1,10,2.0,5.0,0.628074,0.022373,0.598170,0.655195
115,PF,VEN,4.206,4.0,1.351070,1,13,3.0,6.0,0.614188,0.025920,0.580303,0.647728
116,PF,DOM,4.622,5.0,1.074370,2,8,3.0,6.0,0.605371,0.018993,0.580375,0.629186
117,PF,CHL,6.556,6.0,1.566946,4,14,5.0,8.0,0.578223,0.025266,0.544353,0.609701
118,PF,ECU,7.020,7.0,1.423948,3,15,6.0,9.0,0.570517,0.026958,0.535093,0.604283
119,PF,SLV,8.454,8.0,2.492408,2,20,6.0,12.0,0.553933,0.026617,0.519348,0.586168
120,PF,PER,9.482,9.0,1.168350,8,17,8.0,11.0,0.542108,0.019922,0.515763,0.567506
121,PF,URY,10.195,10.0,2.370780,5,18,8.0,14.0,0.535414,0.020056,0.508585,0.559742
122,PF,ARG,11.918,11.0,2.898565,6,23,9.0,16.0,0.525054,0.024140,0.492420,0.553788
123,PF,MEX,12.999,13.0,1.706432,9,20,11.0,15.0,0.512901,0.016831,0.490906,0.534058
124,PF,BOL,15.135,15.0,2.726207,9,26,12.0,19.0,0.501841,0.021966,0.473573,0.529021
125,PF,PRY,15.217,15.0,1.445684,12,20,13.0,17.0,0.500416,0.009662,0.488623,0.513173
126,PF,GTM,15.620,15.0,3.642921,6,26,11.0,21.0,0.496140,0.024713,0.464891,0.528227

##### Probabilidad Top-N RADAR

In [64]:
radar_topn = mc_radar["topn_probabilities"]

radar_topn[
    radar_topn["business_line"] == "PF"
].sort_values("prob_top_5", ascending=False).head(15)

,business_line,country_iso3,prob_top_3,prob_top_5,prob_top_10,prob_top_15
112,PF,CRI,0.908,1.000,1.000,1.000
113,PF,PAN,1.000,1.000,1.000,1.000
114,PF,ESP,0.647,0.947,1.000,1.000
115,PF,VEN,0.265,0.872,0.999,1.000
116,PF,DOM,0.162,0.817,1.000,1.000
117,PF,CHL,0.000,0.213,0.969,1.000
118,PF,SLV,0.015,0.079,0.803,0.987
119,PF,ECU,0.003,0.069,0.964,1.000
120,PF,URY,0.000,0.002,0.673,0.963
121,PF,GUY,0.000,0.001,0.067,0.327
138,PF,TTO,0.000,0.000,0.000,0.000
137,PF,SUR,0.000,0.000,0.000,0.023
136,PF,PRY,0.000,0.000,0.000,0.586
135,PF,PER,0.000,0.000,0.804,0.998
131,PF,HTI,0.000,0.000,0.000,0.000

##### Probabilidad por banda RADAR

In [65]:
radar_tiers = mc_radar["tier_probabilities"]

radar_tiers[
    radar_tiers["business_line"] == "PF"
].sort_values(["Alta", "Media-alta"], ascending=False).head(15)

tier business_line country_iso3   Alta  Media-alta  Media   Baja
120             PF          CRI  1.000       0.000  0.000  0.000
131             PF          PAN  1.000       0.000  0.000  0.000
123             PF          ESP  0.947       0.053  0.000  0.000
139             PF          VEN  0.872       0.127  0.001  0.000
121             PF          DOM  0.817       0.183  0.000  0.000
119             PF          CHL  0.213       0.765  0.022  0.000
134             PF          SLV  0.079       0.808  0.106  0.007
122             PF          ECU  0.069       0.916  0.015  0.000
137             PF          URY  0.002       0.801  0.189  0.008
125             PF          GUY  0.001       0.098  0.284  0.617
132             PF          PER  0.000       0.944  0.055  0.001
112             PF          ARG  0.000       0.611  0.294  0.095
124             PF          GTM  0.000       0.148  0.458  0.394
126             PF          HND  0.000       0.146  0.333  0.521
129             PF          MEX  0.000       0.137  0.826  0.037

##### Robustez de correlaciones entre líneas RADAR

In [66]:
mc_radar["line_correlation_robustness"]

,line_a,line_b,mean_spearman,median_spearman,std_spearman,p10_spearman,p90_spearman,min_spearman,max_spearman
0,AD,BD,0.882196,0.885331,0.040759,0.828079,0.932129,0.694581,0.967159
1,PF,BD,0.873338,0.898194,0.086703,0.752053,0.954023,0.357964,0.989053
2,IB,CIB,0.870108,0.873016,0.047722,0.808429,0.929009,0.681445,0.971538
3,AD,CIB,0.792564,0.795293,0.058298,0.711932,0.864258,0.608101,0.932677
4,IB,PF,0.784388,0.793377,0.084669,0.670991,0.886152,0.435687,0.950739
5,IB,AD,0.783620,0.786535,0.059818,0.701697,0.856596,0.592775,0.937603
6,IB,BD,0.778672,0.784893,0.067414,0.686809,0.866995,0.561029,0.917351
7,PF,AD,0.748851,0.762999,0.094679,0.624412,0.853311,0.324576,0.939792
8,BD,CIB,0.746769,0.749863,0.080174,0.637110,0.851122,0.486043,0.926108
9,PF,CIB,0.721955,0.724138,0.100233,0.590586,0.849589,0.399562,0.935961

##### Distribución de alpha/beta/gamma

In [67]:
mc_radar["composite_weight_distribution"]

         alpha      beta     gamma
mean  0.598037  0.301779  0.100184
std   0.040219  0.038243  0.024766
min   0.462461  0.177318  0.035772
max   0.732123  0.425644  0.277558

#### Tabla ejecutiva final

In [73]:
from typing import Optional, Union


def _coerce_base_ranking_to_dataframe(
    base_ranking: Union[pd.DataFrame, pd.Series],
    score_col: Optional[str] = None,
) -> pd.DataFrame:
    """Convierte ranking base RADAR a DataFrame estándar.

    Soporta:
    1. DataFrame con country_iso3, radar_score y rank.
    2. DataFrame indexado por country_iso3.
    3. Series indexada por country_iso3 con score RADAR.

    Returns:
        DataFrame con columnas:
        country_iso3, base_radar_score, base_rank.
    """

    if isinstance(base_ranking, pd.Series):
        base = base_ranking.copy()

        if base.index.name is None:
            base.index.name = "country_iso3"

        base_df = base.rename("base_radar_score").reset_index()

        base_df["base_rank"] = (
            base_df["base_radar_score"]
            .rank(ascending=False, method="min")
            .astype(int)
        )

        return base_df[["country_iso3", "base_radar_score", "base_rank"]]

    base = base_ranking.copy()

    if "country_iso3" not in base.columns:
        base = base.reset_index()

        if "index" in base.columns:
            base = base.rename(columns={"index": "country_iso3"})

    if score_col is None:
        candidate_score_cols = [
            "radar_score",
            "score",
            "final_score",
            "value",
        ]

        score_col = next(
            (col for col in candidate_score_cols if col in base.columns),
            None,
        )

    if score_col is None:
        raise ValueError(
            "No se pudo inferir columna de score en base_ranking. "
            f"Columnas disponibles: {list(base.columns)}"
        )

    if "rank" not in base.columns:
        base["rank"] = (
            base[score_col]
            .rank(ascending=False, method="min")
            .astype(int)
        )

    base = base.rename(
        columns={
            score_col: "base_radar_score",
            "rank": "base_rank",
        }
    )

    return base[["country_iso3", "base_radar_score", "base_rank"]]


def build_mc_executive_table(
    base_ranking: Union[pd.DataFrame, pd.Series],
    mc_rank_robustness: pd.DataFrame,
    mc_topn: pd.DataFrame,
    mc_tiers: pd.DataFrame,
    business_line: str,
    score_col: Optional[str] = None,
) -> pd.DataFrame:
    """Construye tabla ejecutiva de robustez Monte Carlo para una línea.

    Combina:
    - ranking base RADAR;
    - distribución Monte Carlo de rankings;
    - probabilidades Top-N;
    - probabilidades por banda.
    """

    base = _coerce_base_ranking_to_dataframe(
        base_ranking=base_ranking,
        score_col=score_col,
    )

    robustness = mc_rank_robustness[
        mc_rank_robustness["business_line"] == business_line
    ].copy()

    topn = mc_topn[
        mc_topn["business_line"] == business_line
    ].copy()

    tiers = mc_tiers[
        mc_tiers["business_line"] == business_line
    ].copy()

    out = (
        base
        .merge(
            robustness,
            on="country_iso3",
            how="left",
        )
        .merge(
            topn,
            on=["business_line", "country_iso3"],
            how="left",
        )
        .merge(
            tiers,
            on=["business_line", "country_iso3"],
            how="left",
        )
    )

    return out.sort_values("base_rank").reset_index(drop=True)

In [75]:
base_pf = results["radar_by_line"]["PF"]

print(type(base_pf))
print(base_pf.head())
print("index name:", getattr(base_pf.index, "name", None))
print("index dtype:", base_pf.index.dtype)

<class 'pandas.core.series.Series'>
19    0.697524
8     0.638575
9     0.604111
11    0.628794
7     0.578110
Name: PF, dtype: float64
index name: None
index dtype: int64

In [76]:
base_pf_series = results["radar_by_line"]["PF"].copy()

countries_eval = list(decision_matrix_mc.index)

if len(base_pf_series) != len(countries_eval):
    raise ValueError(
        f"La longitud de la serie PF ({len(base_pf_series)}) no coincide "
        f"con el número de países evaluados ({len(countries_eval)})."
    )

base_pf = pd.DataFrame(
    {
        "country_iso3": countries_eval,
        "radar_score": base_pf_series.values,
    }
)

base_pf["country_iso3"] = base_pf["country_iso3"].astype(str).str.strip()

base_pf["rank"] = (
    base_pf["radar_score"]
    .rank(ascending=False, method="min")
    .astype(int)
)

base_pf = base_pf.sort_values("rank").reset_index(drop=True)

base_pf.head(15)

   country_iso3  radar_score  rank
0           ARG     0.697524     1
1           BHS     0.638575     2
2           BOL     0.628794     3
3           DOM     0.615954     4
4           BLZ     0.604111     5
5           BRA     0.578110     6
6           BRB     0.568597     7
7           ESP     0.551739     8
8           CAN     0.540742     9
9           GTM     0.534801    10
10          MEX     0.525299    11
11          CHL     0.509916    12
12          NIC     0.499951    13
13          JAM     0.499860    14
14          ECU     0.494083    15

In [77]:
pf_mc_exec = build_mc_executive_table(
    base_ranking=base_pf,
    mc_rank_robustness=mc_radar["rank_robustness"],
    mc_topn=mc_radar["topn_probabilities"],
    mc_tiers=mc_radar["tier_probabilities"],
    business_line="PF",
    score_col="radar_score",
)

pf_mc_exec.head(15)

,country_iso3,base_radar_score,base_rank,business_line,mean_rank,median_rank,std_rank,min_rank,max_rank,p10_rank,...,p10_score,p90_score,prob_top_3,prob_top_5,prob_top_10,prob_top_15,Alta,Media-alta,Media,Baja
0,ARG,0.697524,1,PF,11.918,11.0,2.898565,6,23,9.0,...,0.492420,0.553788,0.000,0.000,0.335,0.841,0.000,0.611,0.294,0.095
1,BHS,0.638575,2,PF,23.475,24.0,1.947606,10,27,21.0,...,0.416982,0.465745,0.000,0.000,0.001,0.004,0.000,0.001,0.004,0.995
2,BOL,0.628794,3,PF,15.135,15.0,2.726207,9,26,12.0,...,0.473573,0.529021,0.000,0.000,0.022,0.585,0.000,0.053,0.656,0.291
3,DOM,0.615954,4,PF,4.622,5.0,1.074370,2,8,3.0,...,0.580375,0.629186,0.162,0.817,1.000,1.000,0.817,0.183,0.000,0.000
4,BLZ,0.604111,5,PF,26.067,27.0,1.256220,20,27,24.0,...,0.400375,0.441460,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.000
5,BRA,0.578110,6,PF,23.668,24.0,2.395311,13,27,20.0,...,0.412132,0.467521,0.000,0.000,0.000,0.005,0.000,0.000,0.009,0.991
6,BRB,0.568597,7,PF,22.778,23.0,2.662669,7,27,20.0,...,0.421993,0.470183,0.000,0.000,0.001,0.014,0.000,0.001,0.025,0.974
7,ESP,0.551739,8,PF,3.347,3.0,1.247456,1,10,2.0,...,0.598170,0.655195,0.647,0.947,1.000,1.000,0.947,0.053,0.000,0.000
8,CAN,0.540742,9,PF,19.489,20.0,3.511155,9,26,14.0,...,0.432715,0.505421,0.000,0.000,0.008,0.156,0.000,0.014,0.205,0.781
9,GTM,0.534801,10,PF,15.620,15.0,3.642921,6,26,11.0,...,0.464891,0.528227,0.000,0.000,0.089,0.510,0.000,0.148,0.458,0.394
10,MEX,0.525299,11,PF,12.999,13.0,1.706432,9,20,11.0,...,0.490906,0.534058,0.000,0.000,0.045,0.905,0.000,0.137,0.826,0.037
11,CHL,0.509916,12,PF,6.556,6.0,1.566946,4,14,5.0,...,0.544353,0.609701,0.000,0.213,0.969,1.000,0.213,0.765,0.022,0.000
12,NIC,0.499951,13,PF,17.949,18.0,4.000550,7,27,12.0,...,0.453207,0.523581,0.000,0.000,0.038,0.245,0.000,0.060,0.299,0.641
13,JAM,0.499860,14,PF,22.535,22.0,2.260063,10,27,20.0,...,0.427299,0.471350,0.000,0.000,0.002,0.006,0.000,0.002,0.010,0.988
14,ECU,0.494083,15,PF,7.020,7.0,1.423948,3,15,6.0,...,0.535093,0.604283,0.003,0.069,0.964,1.000,0.069,0.916,0.015,0.000

In [78]:
print("Filas base:", len(base_pf))
print("Filas tabla ejecutiva:", len(pf_mc_exec))

missing_mc = pf_mc_exec[
    pf_mc_exec["mean_rank"].isna()
]["country_iso3"].tolist()

print("Países sin resultados Monte Carlo:", missing_mc)

Filas base: 28
Filas tabla ejecutiva: 28
Países sin resultados Monte Carlo: []

In [79]:
def build_base_radar_by_line_from_series(
    radar_by_line: dict,
    countries_eval: list,
) -> dict:
    """Convierte results['radar_by_line'] en DataFrames por línea.

    Args:
        radar_by_line: Diccionario {linea: Series} con scores RADAR.
        countries_eval: Lista de países en el mismo orden usado por el scoring.

    Returns:
        Diccionario {linea: DataFrame} con country_iso3, radar_score, rank.
    """

    out = {}

    for business_line, score_series in radar_by_line.items():
        if len(score_series) != len(countries_eval):
            raise ValueError(
                f"La longitud de {business_line} ({len(score_series)}) no coincide "
                f"con países evaluados ({len(countries_eval)})."
            )

        df = pd.DataFrame(
            {
                "country_iso3": countries_eval,
                "radar_score": score_series.values,
            }
        )

        df["country_iso3"] = df["country_iso3"].astype(str).str.strip()

        df["rank"] = (
            df["radar_score"]
            .rank(ascending=False, method="min")
            .astype(int)
        )

        out[business_line] = (
            df
            .sort_values("rank")
            .reset_index(drop=True)
        )

    return out

In [84]:
from typing import Dict, Optional, List

import pandas as pd


def build_base_radar_by_line(
    radar_by_line,
    countries_eval: Optional[List[str]] = None,
    business_lines: Optional[List[str]] = None,
) -> Dict[str, pd.DataFrame]:
    """Convierte results['radar_by_line'] en DataFrames por línea.

    Soporta:
    1. DataFrame ancho:
       country_iso3 | IB | PF | AD | BD | CIB

    2. Dict:
       {linea: Series}

    3. Dict:
       {linea: DataFrame}

    Returns:
        Dict {business_line: DataFrame} con:
        country_iso3, radar_score, rank.
    """

    out: Dict[str, pd.DataFrame] = {}

    # ------------------------------------------------------------------
    # Caso 1: radar_by_line es DataFrame ancho
    # ------------------------------------------------------------------
    if isinstance(radar_by_line, pd.DataFrame):
        df = radar_by_line.copy()

        if "country_iso3" not in df.columns:
            df = df.reset_index()

            if "index" in df.columns:
                df = df.rename(columns={"index": "country_iso3"})

        if "country_iso3" not in df.columns:
            raise ValueError(
                "radar_by_line es DataFrame pero no contiene country_iso3. "
                f"Columnas disponibles: {list(df.columns)}"
            )

        df["country_iso3"] = df["country_iso3"].astype(str).str.strip()

        if business_lines is None:
            business_lines = [
                col for col in df.columns
                if col != "country_iso3"
            ]

        for business_line in business_lines:
            if business_line not in df.columns:
                continue

            tmp = df[["country_iso3", business_line]].copy()
            tmp = tmp.rename(columns={business_line: "radar_score"})

            tmp["radar_score"] = pd.to_numeric(
                tmp["radar_score"],
                errors="coerce",
            )

            tmp = tmp.dropna(subset=["radar_score"])

            tmp["rank"] = (
                tmp["radar_score"]
                .rank(ascending=False, method="min")
                .astype(int)
            )

            out[business_line] = (
                tmp
                .sort_values("rank")
                .reset_index(drop=True)
            )

        return out

    # ------------------------------------------------------------------
    # Caso 2 y 3: radar_by_line es dict
    # ------------------------------------------------------------------
    if isinstance(radar_by_line, dict):
        for business_line, obj in radar_by_line.items():

            # Ignorar llaves que no son líneas de negocio.
            if business_line == "country_iso3":
                continue

            # ----------------------------------------------------------
            # Caso 2A: valor es Series
            # ----------------------------------------------------------
            if isinstance(obj, pd.Series):
                score_series = obj.copy()

                # Si la Series tiene índice no numérico, usarlo como país.
                if not pd.api.types.is_integer_dtype(score_series.index):
                    tmp = (
                        score_series
                        .rename("radar_score")
                        .reset_index()
                    )

                    if tmp.columns[0] != "country_iso3":
                        tmp = tmp.rename(
                            columns={tmp.columns[0]: "country_iso3"}
                        )

                else:
                    # Si la Series tiene índice numérico, necesitamos countries_eval.
                    if countries_eval is None:
                        raise ValueError(
                            f"{business_line} es Series con índice numérico. "
                            "Debe pasar countries_eval o usar un DataFrame con country_iso3."
                        )

                    if len(score_series) != len(countries_eval):
                        raise ValueError(
                            f"La longitud de {business_line} ({len(score_series)}) "
                            f"no coincide con countries_eval ({len(countries_eval)})."
                        )

                    tmp = pd.DataFrame(
                        {
                            "country_iso3": countries_eval,
                            "radar_score": score_series.values,
                        }
                    )

                tmp["country_iso3"] = tmp["country_iso3"].astype(str).str.strip()
                tmp["radar_score"] = pd.to_numeric(
                    tmp["radar_score"],
                    errors="coerce",
                )

                tmp = tmp.dropna(subset=["radar_score"])

                tmp["rank"] = (
                    tmp["radar_score"]
                    .rank(ascending=False, method="min")
                    .astype(int)
                )

                out[business_line] = (
                    tmp
                    .sort_values("rank")
                    .reset_index(drop=True)
                )

            # ----------------------------------------------------------
            # Caso 2B: valor es DataFrame
            # ----------------------------------------------------------
            elif isinstance(obj, pd.DataFrame):
                tmp = obj.copy()

                if "country_iso3" not in tmp.columns:
                    tmp = tmp.reset_index()

                    if "index" in tmp.columns:
                        tmp = tmp.rename(columns={"index": "country_iso3"})

                if "country_iso3" not in tmp.columns:
                    raise ValueError(
                        f"{business_line} es DataFrame pero no contiene country_iso3."
                    )

                candidate_score_cols = [
                    "radar_score",
                    "score",
                    "final_score",
                    business_line,
                    "value",
                ]

                score_col = next(
                    (col for col in candidate_score_cols if col in tmp.columns),
                    None,
                )

                if score_col is None:
                    raise ValueError(
                        f"No se pudo inferir columna score para {business_line}. "
                        f"Columnas: {list(tmp.columns)}"
                    )

                tmp = tmp[["country_iso3", score_col]].copy()
                tmp = tmp.rename(columns={score_col: "radar_score"})

                tmp["country_iso3"] = tmp["country_iso3"].astype(str).str.strip()
                tmp["radar_score"] = pd.to_numeric(
                    tmp["radar_score"],
                    errors="coerce",
                )

                tmp = tmp.dropna(subset=["radar_score"])

                tmp["rank"] = (
                    tmp["radar_score"]
                    .rank(ascending=False, method="min")
                    .astype(int)
                )

                out[business_line] = (
                    tmp
                    .sort_values("rank")
                    .reset_index(drop=True)
                )

            else:
                raise TypeError(
                    f"Tipo no soportado para {business_line}: {type(obj)}"
                )

        return out

    raise TypeError(
        "radar_by_line debe ser DataFrame o dict. "
        f"Tipo recibido: {type(radar_by_line)}"
    )

In [86]:
base_radar_by_line = build_base_radar_by_line(
    radar_by_line=results["radar_by_line"]
)

In [87]:
pf_mc_exec = build_mc_executive_table(
    base_ranking=base_radar_by_line["PF"],
    mc_rank_robustness=mc_radar["rank_robustness"],
    mc_topn=mc_radar["topn_probabilities"],
    mc_tiers=mc_radar["tier_probabilities"],
    business_line="PF",
    score_col="radar_score",
)

pf_mc_exec.head(15)

,country_iso3,base_radar_score,base_rank,business_line,mean_rank,median_rank,std_rank,min_rank,max_rank,p10_rank,...,p10_score,p90_score,prob_top_3,prob_top_5,prob_top_10,prob_top_15,Alta,Media-alta,Media,Baja
0,PAN,0.697524,1,PF,1.017,1.0,0.129336,1,2,1.0,...,0.670088,0.728815,1.000,1.000,1.000,1.000,1.000,0.000,0.000,0.000
1,CRI,0.638575,2,PF,2.465,2.0,0.658186,2,4,2.0,...,0.618087,0.660862,0.908,1.000,1.000,1.000,1.000,0.000,0.000,0.000
2,ESP,0.628794,3,PF,3.347,3.0,1.247456,1,10,2.0,...,0.598170,0.655195,0.647,0.947,1.000,1.000,0.947,0.053,0.000,0.000
3,VEN,0.615954,4,PF,4.206,4.0,1.351070,1,13,3.0,...,0.580303,0.647728,0.265,0.872,0.999,1.000,0.872,0.127,0.001,0.000
4,DOM,0.604111,5,PF,4.622,5.0,1.074370,2,8,3.0,...,0.580375,0.629186,0.162,0.817,1.000,1.000,0.817,0.183,0.000,0.000
5,CHL,0.578110,6,PF,6.556,6.0,1.566946,4,14,5.0,...,0.544353,0.609701,0.000,0.213,0.969,1.000,0.213,0.765,0.022,0.000
6,ECU,0.568597,7,PF,7.020,7.0,1.423948,3,15,6.0,...,0.535093,0.604283,0.003,0.069,0.964,1.000,0.069,0.916,0.015,0.000
7,SLV,0.551739,8,PF,8.454,8.0,2.492408,2,20,6.0,...,0.519348,0.586168,0.015,0.079,0.803,0.987,0.079,0.808,0.106,0.007
8,PER,0.540742,9,PF,9.482,9.0,1.168350,8,17,8.0,...,0.515763,0.567506,0.000,0.000,0.804,0.998,0.000,0.944,0.055,0.001
9,URY,0.534801,10,PF,10.195,10.0,2.370780,5,18,8.0,...,0.508585,0.559742,0.000,0.002,0.673,0.963,0.002,0.801,0.189,0.008
10,ARG,0.525299,11,PF,11.918,11.0,2.898565,6,23,9.0,...,0.492420,0.553788,0.000,0.000,0.335,0.841,0.000,0.611,0.294,0.095
11,MEX,0.509916,12,PF,12.999,13.0,1.706432,9,20,11.0,...,0.490906,0.534058,0.000,0.000,0.045,0.905,0.000,0.137,0.826,0.037
12,PRY,0.499951,13,PF,15.217,15.0,1.445684,12,20,13.0,...,0.488623,0.513173,0.000,0.000,0.000,0.586,0.000,0.000,0.760,0.240
13,BOL,0.499860,14,PF,15.135,15.0,2.726207,9,26,12.0,...,0.473573,0.529021,0.000,0.000,0.022,0.585,0.000,0.053,0.656,0.291
14,USA,0.494083,15,PF,15.770,16.0,3.656839,6,24,11.0,...,0.460809,0.526995,0.000,0.000,0.074,0.456,0.000,0.132,0.380,0.488

##### Persistencia de resultados

In [88]:
scores_dir = resolve_data_path(configs["settings"]["data"]["scores_path"])
scores_dir.mkdir(parents=True, exist_ok=True)

mc_radar["rank_robustness"].to_parquet(
    scores_dir / "mc_radar_rank_robustness_latest.parquet",
    index=False,
)

mc_radar["topn_probabilities"].to_parquet(
    scores_dir / "mc_radar_topn_probabilities_latest.parquet",
    index=False,
)

mc_radar["tier_probabilities"].to_parquet(
    scores_dir / "mc_radar_tier_probabilities_latest.parquet",
    index=False,
)

mc_radar["line_correlation_robustness"].to_parquet(
    scores_dir / "mc_radar_line_correlation_robustness_latest.parquet",
    index=False,
)

mc_topsis["rank_robustness"].to_parquet(
    scores_dir / "mc_topsis_rank_robustness_latest.parquet",
    index=False,
)